name: release-please
on:
  push:
    branches: [main]          # run after every merge to main
    
permissions:
  contents: write             # allow tag + release
  pull-requests: write        # allow the bot to open/refresh PRs
  actions: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}